### ISSUE TITLE
JEST TypeError: exports.overwriteWith is not a function

### ISSUE THREAD

**Issue by salehi186** [alexfernandez/loadtest#168]
When load test is called inside the jest this error is happening
TypeError: exports.overwriteWith is not a function

`FAIL  tests/stress/status.load.test.ts
  ● Test suite failed to run

    TypeError: exports.overwriteWith is not a function

      at Object.<anonymous> (../../node_modules/prototypes/index.js:15:9)
      at Object.<anonymous> (../../node_modules/loadtest/lib/loadtest.js:10:1)
`

**Comment by salehi186** [comment]
the fix would be easy but not inside this repo 
in your prototypes repo should be change index.js to 
`
'use strict';

/**
 * Export all prototypes.
 * (C) 2013 Alex Fernández.
 */

// requires
require('./lib/string.js');
require('./lib/array.js');
var mathLib = require('./lib/math.js');
var objectLib = require('./lib/object.js');
exports= {...objectLib,...mathLib}
// exports
// exports.overwriteWith(objectLib);
// exports.overwriteWith(mathLib);
`

**Comment by alexfernandez** [comment]
PRs always welcome, also in [prototypes](https://github.com/alexfernandez/prototypes) ;)

**Comment by salehi186** [comment]
@alexfernandez  I have made a PR for prototypes. 
Actually it would be too helpful if u could merge it in your repo.

**Comment by Piranit** [comment]
Hi
I also encountered this problem
@alexfernandez, can you merge @salehi186 solution into [prototypes](https://github.com/alexfernandez/prototypes) repo?
Thx.

**Comment by alexfernandez** [comment]
@Piranit and @salehi186 I hesitate to merge his solution because it would only work with Node.js v8 and later, while loadtest is supposed to work with v0.12. What version of Node.js are you using? For me, `overwriteWith()` works even with v12. Do you have some minimal example that I can check out?

**Comment by rgavinc** [comment]
I'm also running into this issue. Was anyone able to find a solution that works with node v0.12? @Piranit  @salehi186 @alexfernandez

**Comment by alexfernandez** [comment]
At this point we might as well suppose that new versions of loadtest will only run with modern versions of Node.js. If interest is high enough I will merge the PR on `prototypes`. Opinions? Please vote with :+1: or :-1: as a reaction to this comment.

**Comment by alexfernandez** [comment]
Published as loadtest@4.0.0. Please update and report back!

**Comment by alexfernandez** [comment]
Closing, please reopen if needed.
